/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-29 04:58:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class wk_005finsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1671259522000L));
    _jspx_dependants.put("jar:file:/Users/l/hrdkorea/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/jsp_workout/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

	String num = request.getParameter("num");
	
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"workout\">\n");
      out.write("		<form name=\"wk_insert\" action=\"insert\">\n");
      out.write("			<div class=\"day\">\n");
      out.write("				<table>\n");
      out.write("					<tr>\n");
      out.write("						<th>고객 DB 번호 : ");
      out.print(num);
      out.write(" <input type=\"hidden\"\n");
      out.write("							name=\"user_number\" value=\"");
      out.print(num);
      out.write("\">\n");
      out.write("						</th>\n");
      out.write("						<th>오늘의 운동 기록</th>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th>운동 부위 <input type=\"text\" name=\"wk_part\" maxlength=\"20\">\n");
      out.write("						</th>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<th>운동명</th>\n");
      out.write("						<th>무게</th>\n");
      out.write("						<th>횟수</th>\n");
      out.write("						<th>세트 수</th>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"text\" name=\"ex_name\" maxlength=\"40\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_weight\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_reps\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_sets\" maxlength=\"20\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"text\" name=\"ex_name\" maxlength=\"40\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_weight\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\"  name=\"ex_reps\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\"  name=\"ex_sets\" maxlength=\"20\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"text\" name=\"ex_name\" maxlength=\"40\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_weight\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_reps\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_sets\" maxlength=\"20\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"text\" name=\"ex_name\" maxlength=\"40\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_weight\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_reps\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_sets\" maxlength=\"20\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"text\" name=\"ex_name\" maxlength=\"40\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_weight\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_reps\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_sets\" maxlength=\"20\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td><input type=\"text\" name=\"ex_name\" maxlength=\"40\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_weight\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_reps\" maxlength=\"20\"></td>\n");
      out.write("						<td><input type=\"text\" name=\"ex_sets\" maxlength=\"20\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td colspan=\"1\">\n");
      out.write("							<button onclick=\"chk_form(); return false;\">운동 종료</button>\n");
      out.write("							<button onclick=\"chk_cancel(); return false;\">운동 취소</button>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("		<p>\n");
      out.write("			사람이 자신의 몸이 가질 수 있는 마음과 강함을 알지 못하고 <br> 늙어버리는 것은 안타까운 일이다 <br>\n");
      out.write("			<b> 소크라테스 </b>\n");
      out.write("		</p>\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("			<button> 홈으로 </button>\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\" src=\"./script.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
